"""add retry fields

Revision ID: 6764f8c8a8b8
Revises: f065b93a5f73
Create Date: 2026-07-17 01:33:01.651552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6764f8c8a8b8'
down_revision: Union[str, Sequence[str], None] = 'f065b93a5f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('next_retry_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('last_error', sa.String(), nullable=True))
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('jobs', 'last_error')
    op.drop_column('jobs', 'next_retry_at')
    # ### end Alembic commands ###
